AZURE_LOCATION: 'centralindia'
RESOURCE_NAME_PREFIX: 'exp'
ENVIRONMENT_TAG: 'dev'
DEPLOYMENT_NAME: 'ase-dev-deployment'
VM_USERNAME: 'agent'
ACCOUNT_NAME: 'github.com/extentplustech'
CICD_AGENT_TYPE: 'azuredevops'
CERT_TYPE: 'selfsigned'
